[tools]
terraform = "1.8.2"
node = "24.12.0"
python = "3.13.2"
hugo = "extended_0.110.0"
rust = "1.86.0"
java = "openjdk-24.0.1"
bun = "1.3.0"
deno = "2.5.4"
go = "1.22.2"
lua = "5.4.7"
usage = "latest"

"npm:@github/copilot" = "latest"
"npm:oxlint" = "latest"
"npm:oxlint-tsgolint" = "latest"

[settings]
activate_aggressive = true
experimental = true
npm.bun = true
idiomatic_version_file_enable_tools = ["python"]
