[tools]
terraform = "1.8.2"
node = "24.12.0"
python = "3.14.2"
rust = "1.86.0"
java = "openjdk-24.0.1"
bun = "1.3.0"
deno = "2.5.4"
go = "1.22.2"
usage = "latest"

"npm:@github/copilot" = "latest"
"npm:oxlint" = "latest"
"npm:oxlint-tsgolint" = "latest"
"npm:corepack" = "latest"

[settings]
activate_aggressive = true
experimental = true
npm.package_manager = "bun"
idiomatic_version_file_enable_tools = ["node", "python"]
